### Creating a user
POST http://localhost:1234/signup
Content-Type: application/json

{
    "name": "user2",
    "email": "test2@test.com",
    "password": "password",
    "confirmPassword": "password"
}

### login a user
POST http://localhost:1234/signin
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "password",
    "confirmPassword": "password"
}

### Find all Users
GET http://localhost:1234/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwOTQwMTgxOCwiZXhwIjoxNzA5NDA1NDE4fQ._QtURDYUC_PXmiOkTZkvOThdGUZqPmbE8ecls19Vz6k